/**
 * SQL DDL statements for the billing service's tables.
 *
 * In a real-world scenario these would be generated by `futonic/cli`,
 * but we hardcode them here for the example. Table names are prefixed
 * with `billing_` to match the service ID.
 */

export const SQLITE_UP = `
CREATE TABLE IF NOT EXISTS billing_invoices (
	id TEXT PRIMARY KEY NOT NULL,
	customer_id TEXT NOT NULL,
	amount REAL NOT NULL,
	currency TEXT NOT NULL DEFAULT 'USD',
	status TEXT NOT NULL DEFAULT 'draft',
	due_date TEXT,
	created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_line_items (
	id TEXT PRIMARY KEY NOT NULL,
	invoice_id TEXT NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
	description TEXT NOT NULL,
	quantity REAL NOT NULL,
	unit_price REAL NOT NULL
);
`;
